version: "3.0"
services:
  db:
    container_name: todo-app-db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
